export {NavbarCreate} from './nav';
export {Header} from './header';
export {OurService} from './our-section';
export {WhyUs} from './why-us';
export {Testimonial} from './testimonial';
export {TestimonialContent} from './testimonial-content';
export {GettingStarted} from './getting-started';
export {Faq} from './faq';
export {Footer} from './footer';